### PR TITLE
second commit

### PR DESCRIPTION
**Pull request by Nchedubem**
Please Kindly Review my work
@Promise-j
@ChidiPatrick
Group A

### CODE REVIEW

**Review by promise-J — CHANGES_REQUESTED** [review]
Hide the nav links and display the menu icon. Great work

**Comment by Nchedubem** [comment]
I have corrected it

**Review by promise-J — APPROVED** [review]
This task has no footer
Great responsiveness.
CLIMATE ACTION NETWRK (CAN)
The Netwrk could have been a typo. 
Submit and merge

**Comment by Nchedubem** [comment]
I have made the correct
Please Sir Kindly Review my work
Thanks & Regards

**Review by promise-J — APPROVED** [review]
Cleared! Please merge

**Pull request merged**
